### ISSUE TITLE
"No such image" when deploying the OPC twin module

### ISSUE THREAD

**Issue by djdtimit** [Azure/azure-iiot-opc-twin-module#4]
Hey,

I followed this tutorial [https://github.com/Azure/azure-iiot-components/blob/master/docs/twin/howto-modules.md](url) to deploy a OPC twin module on my edge device (local computer using windows containers). The Prerequisites are met and the OPCPublisher is working. 

But everytime I got the following error: "No such image" after pulling the container (see below).
![image](https://user-images.githubusercontent.com/48924579/55173838-4c51db80-5174-11e9-9f1a-2648d79bab57.png)

What am I doing wrong?

Thanks

**Comment by marcschier** [comment]
We might have had some issues in our backend.   I just tried and pulled it down just fine.  Note we just released v2 which is now "latest".  v2 module is not backwards compatible with v1 services, but if you are coming from azure-iiot-components repo, you are already on v2. 

```
D:\git\azure\azure-iiot-components>docker pull mcr.microsoft.com/iotedge/opc-twin:latest
latest: Pulling from iotedge/opc-twin
27833a3ba0a5: Already exists
06b9d09cd961: Already exists
62687e83c92c: Already exists
eb266ff93600: Already exists
7078f2b764c5: Pull complete
d73fd2128f9c: Pull complete
Digest: sha256:667020054885a65bde4fa31be7f7fa8aa4678223170e2faec5410e6db54d726d
Status: Downloaded newer image for mcr.microsoft.com/iotedge/opc-twin:latest

D:\git\azure\azure-iiot-components>docker pull mcr.microsoft.com/iotedge/opc-twin:2
2: Pulling from iotedge/opc-twin
Digest: sha256:667020054885a65bde4fa31be7f7fa8aa4678223170e2faec5410e6db54d726d
Status: Downloaded newer image for mcr.microsoft.com/iotedge/opc-twin:2

D:\git\azure\azure-iiot-components>docker pull mcr.microsoft.com/iotedge/opc-twin:1.0.1
1.0.1: Pulling from iotedge/opc-twin
a5a6f2f73cd8: Pull complete
0cf9e2b1f8e3: Pull complete
23109ffc4a85: Pull complete
6c5c45ca2817: Pull complete
360265a420c2: Pull complete
c2986b80cb1b: Pull complete
Digest: sha256:b7a014fb1eca75812437978919927b84865e4f0cbb26f733d17c779c1598a63d
Status: Downloaded newer image for mcr.microsoft.com/iotedge/opc-twin:1.0.1
```
